### ISSUE TITLE
minecraft:spider Crash

### ISSUE THREAD

**Issue by Daejangnamu** [Thelnfamous1/Dungeons-Mobs#37] opened 2021-08-11 21:35 UTC
forge-1.16.5-36.2.2

mod list
jei-1.16.5-7.7.1.118
dungeons_mobs-1.16.5-1.0.10

log: https://gist.github.com/Daejangnamu/c2474390e6595d2e3c6f8e4b56f31dab

**Comment by Patrigan** [comment] 2021-09-19 14:26
The log is no longer accessible, can you reprovide it.

**Comment by Patrigan** [comment] 2021-09-19 14:30
Possible duplicate of an earlier bug with ranged spiders disabled?

**Comment by BraveCaperCat** [comment] 2022-03-22 20:54
Close immediately, not enough info!

**Comment by Patrigan** [comment] 2022-11-18 11:11
Ranged spiders no longer crash the game

**Closed as completed by Patrigan** 2022-11-18 11:11 UTC
