### ISSUE TITLE
the textures are miss placed with a resource pack

### ISSUE THREAD

**Issue by JinxLaJoker** [Thelnfamous1/Dungeons-Mobs#52] opened 2021-11-15 04:13 UTC
this only happens with the skeletons that reply on the textures of the game, the resource pack has the skeletons textures at 128x64 making the mod not work with 
for example - https://user-images.githubusercontent.com/42846339/141721243-6c3b468b-a505-4834-8897-505dc82db336.png

**Comment by DarkSoulMastery** [comment] 2021-11-28 22:08
This is probably caused by certain mods or resource pack

**Comment by Patrigan** [comment] 2022-11-18 11:06
Does this issue still exist with latest betas?

**Comment by Patrigan** [comment] 2023-01-13 09:41
Closing this as we've changed the way several mobs work and removed the armoured skeletons completely.

**Closed as completed by Patrigan** 2023-01-13 09:41 UTC
